CREATE TABLE Assets (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AssetName NVARCHAR(200) NOT NULL,
    AssetType NVARCHAR(100) NULL,
    Location NVARCHAR(200) NULL,
    Description NVARCHAR(MAX) NULL,
    BlobName NVARCHAR(500) NULL,
    OriginalFileName NVARCHAR(255) NULL,
    ContentType NVARCHAR(150) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
