name: Deploy Node backend to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Deploy backend to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: sparkcpd-asset-api
          package: ./server
