name: Build and deploy Node.js app to Azure Web App - sparkcpd-asset-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9EFD20FFEA424C95BE63F463CEAA09FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2CE37C12C60A4F398AE770CF146B84EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DABE75793A3423694811063275B8D44 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: sparkcpd-asset-api
          slot-name: Production
          package: ./server
